
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_ "server/peakgo/netio"


	_xtest "server/peakgo/netio_test"

)

var tests = []testing.InternalTest{

	{"TestReadHeaderCorrectness", _xtest.TestReadHeaderCorrectness},

	{"TestReadPayloadCorrectness", _xtest.TestReadPayloadCorrectness},

	{"TestReadPayloadEOFReturnsError", _xtest.TestReadPayloadEOFReturnsError},

	{"TestReadPayloadShortRead", _xtest.TestReadPayloadShortRead},

	{"TestReadPayloadBoundaryGuards", _xtest.TestReadPayloadBoundaryGuards},

	{"TestWritePacketCorrectness", _xtest.TestWritePacketCorrectness},

	{"TestNetioReadWritePipeline", _xtest.TestNetioReadWritePipeline},

}

var benchmarks = []testing.InternalBenchmark{

	{"BenchmarkReadHeader", _xtest.BenchmarkReadHeader},

	{"BenchmarkReadPayload", _xtest.BenchmarkReadPayload},

	{"BenchmarkWritePacket", _xtest.BenchmarkWritePacket},

	{"BenchmarkRingBufferPeakGo", _xtest.BenchmarkRingBufferPeakGo},

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "server"
	testdeps.ImportPath = "server/peakgo/netio"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

